site_name: MicroPython Clocks and Watches
site_description: 'Resources for teaching drawing on a clock or watch face. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/micropython-clocks-and-watches'
repo_url: 'https://github.com/dmccreary/micropython-clocks-and-watches'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Setup:
    - Introduction: setup/index.md
    - Desktop Setup: setup/desktop.md
    - Purchasing Parts: setup/02-purchasing-parts.md
    - 7-Wire SPI Cables: setup/display-cable.md
  - Lessons:
    - Introduction: lessons/index.md
    - Hardware Config: lessons/00-hardware-config.md
    - Drawing Coordinates: lessons/01-drawing-coordinates.md
    - Displaying Text: lessons/02-display-text.md
    - Drawing a Clock Face: lessons/03-drawing-face.md
    - Larger Fonts: lessons/04-larger-fonts.md
    - Hardware Config Files: lessons/00-hardware-config.md
    - Get Local Time: lessons/01-get-local-time.md
    - Drawing 7-Segment Digits: lessons/07-drawing-digits.md
    - Digit Functions: lessons/09-digit-functions.md
    - Draw Time Functions: lessons/12-draw-time-functions.md
    - Scale Testing: lessons/15-scale-testing.md
    - Buttons: lessons/05-buttons.md
    - Draw Performance: lessons/06-draw-performance.md
    - Machine Info: lessons/40-machine-info.md
  - Kits:
    - Introduction Kits: kits/index.md
    - kits/ili9341/03-multiple-fonts.md
    - kits/pico-oled/10-draw-seven-segments.md
    - kits/pico-oled/11-draw-thinkness.md
    - kits/pico-oled/15-digital-clock.md
    - LED Strip Kits: 
      - Introduction: kits/led-strips/index.md
      - Binary Clock: kits/led-strips/01-binary-clock.md
      - 7 Segment Clock: kits/led-strips/02-seven-segment-clock.md
    - Pico with OLED:
      - Introduction: kits/pico-oled/index.md
      - Hello World: kits/pico-oled/01-hello-world.md
      - Hello Config: kits/pico-oled/02-hello-config.md
      - Hello Firmware: kits/pico-oled/01-hello-world-firmware.md
      - Display Time: kits/pico-oled/02-display-time.md
      - Display Localtime: kits/pico-oled/03-display-localtime.md
      - Display Localtime Updates: kits/pico-oled/04-display-localtime-updates.md
      - Display Clock Hands:  kits/pico-oled/05-clock-hands.md
    - ILI9341:
      - Introduction: kits/ili9341/index.md
      - Rainbow Test: kits/ili9341/01-rainbow-test.md
      - Hardware Config: kits/ili9341/02-config.md
    - GC9A01:
      - Introduction: kits/gc9a01/index.md
      - Hello World: kits/gc9a01/01-hello-world.md
      - Display Time: kits/gc9a01/02-display-time.md
      - Display Hand: kits/gc9a01//03-display-hand.md
      - Cycle Fonts: kits/gc9a01/04-cycle-fonts.md
      - Draw Ticks: kits/gc9a01/05-draw-ticks.md
      - Watch Face: kits/gc9a01/09-watch-face.md
      - Draw 12 Digits: kits/gc9a01/07-draw-12-digits.md
      - Draw Filled Triangle: kits/gc9a01/08-draw-filled-triangle.md
    - LILYGO SY7789:
      - Introduction: kits/lilygo/index.md
    - Waveshare:
      - Introduction: kits/waveshare/index.md
      - Hello World: kits/waveshare/01-hello-world.md
      - Display Text: kits/waveshare/02-display-text.md
      - Color Lab: kits/waveshare/02-color-test.md
      - Drawing Hands: kits/waveshare/03-drawing-hands.md
      - Font Lab: kits/waveshare/04-5x8-font.md
    - MAX7219: kits/max7219/index.md
  - MicroSims:
    - sims/index.md
    - sims/binary-clock/index.md
  - sims/templates/index.md
    - sims/learning-graph/index.md
    - sims/4-digits/index.md
    - sims/analog-face/index.md
    - sims/learning-graph/index.md
    - sims/seven-segments/index.md
    - sims/themes/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Course Description: prompts/01-course-description.md
    - Concept Enumeration: prompts/02-concept-enumeration.md
    - Concept Dependencies: prompts/03-concept-dependencies.md
  - References: references.md
  - Contact: contact.md
  - faq.md

  - lessons/30-ili9341.md
  - setup/01-desktop.md
  - setup/02-purchsing-parts.md
  - setup/03-approach.md
  - kits/e-ink/index.md
  - kits/led-display/index.md
  - prompts/03-concept-dependency.md
  - prompts/04-concept-taxonomy.md
  - prompts/05-taxonomy-assignment.md



# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  custom_dir: custom-theme
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  extra_css:
    - styles/custom.css
  logo: img/clock-icon.png
  favicon: img/clock-icon.png
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-EKTEBLZ2KP
