site_name: "Clocks and Watches with AI"
site_description: 'Designing and Building and Clock and Watches with MicroPython and AI.  This projects uses low-cost parts, MicroPython and AI to teach computational thinking.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/clocks-and-watches'
repo_url: 'https://github.com/dmccreary/clocks-and-watches'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Setup:
    - Introduction: setup/index.md
    - Desktop Setup: setup/01-desktop.md
    - Purchasing Parts: setup/02-purchasing-parts.md
    - Cable Harness: setup/03-display-cable-harness.md
    - LED Art Clocks: setup/04-led-clocks.md
    - Pico Wireless: setup/06-pico-w-setup.md
    - Sound and Speakers: setup/07-sound.md
    - AI in the Classroom: setup/05-ai-in-the-classroom.md
  - Lessons:
    - Introduction: lessons/index.md
    - Timekeeping Architecture: lessons/01-timekeeping-architecture.md
    - The I2C Bus: lessons/10-i2c-bus.md
    - The SPI Bus: lessons/11-spi-bus.md
    - Screen Drawing:
      - Introduction: lessons/screen-drawing/index.md
      - Drawing Coordinates: lessons/screen-drawing/01-drawing-coordinates.md
      - Displaying Text: lessons/screen-drawing/02-display-text.md
      - Drawing a Clock Face: lessons/screen-drawing/03-drawing-face.md
      - Drawing 7-Segment Digits: lessons/screen-drawing/07-drawing-digits.md
      - Digit Functions: lessons/screen-drawing/09-digit-functions.md
      - Scale Testing: lessons/screen-drawing/15-scale-testing.md
      - Draw Performance: lessons/screen-drawing/06-draw-performance.md
      - Draw Time Functions: lessons/screen-drawing/12-draw-time-functions.md
      - Larger Fonts: lessons/screen-drawing/04-larger-fonts.md
      - Drawing Polygons: lessons/screen-drawing/05-drawing-polygons.md
      - Alarm Icon: lessons/screen-drawing/16-drawing-alarm-icon.md
    - Hardware Config Files: lessons/00-hardware-config.md
    - Get Local Time: lessons/01-get-local-time.md
    - Buttons: lessons/05-buttons.md
    - Manually Setting Time: lessons/06-setting-time.md
    - Real Time Clocks:
      - Introduction: lessons/rtc/index.md
      - About Real Time Clocks: lessons/rtc/13-real-time-clocks.md
      - Testing The RTC: lessons/rtc/testing-the-rtc-type.md
      - RTC Explained: lessons/rtc/13-rtc-explained.md
      - RTC Breadboard Testing: lessons/rtc/50-ds1307-breadboard.md
    - ILI9341 Display: lessons/30-ili9341.md
    - Adding Sound: lessons/60-sound/index.md
    - Digital to Analog Converters:
      - Introduction: lessons/digital-to-analog-converters/index.md
      - Assembly: lessons/digital-to-analog-converters/assembly.md
      - Code: lessons/digital-to-analog-converters/code.md
      - Prompt: lessons/digital-to-analog-converters/prompt.md
    - Machine Info: lessons/40-machine-info.md
    - Shift Registers: lessons/55-shift-registers/index.md
    - Powering Your Clock and Watch: lessons/70-power/index.md
  - Kits:
    - Introduction Kits: kits/index.md
    - Gallery: kits/gallery.md
    - TM1637 LED Kit:
      - Intro: kits/tm1637/index.md
      - Manually Setting Time: kits/tm1637/manual-time-setting.md
      - Running the Clock: kits/tm1637/running-clock.md
    - LED Displays: 
      - Intro: kits/led-displays/index.md
      - Simple TM1637 Display: kits/led-displays/clock-simple.md
      - Shift Register Displays:
        - Intro: kits/shift-register-clock/index.md
        - kits/led-displays/shift-register-displays.md
        - kits/shift-register-clock/clock-main.md
        - kits/shift-register-clock/sample-prompt.md
      - Reference: kits/led-displays/reference.md
    - NeoPixel Clocks: 
      - Introduction: kits/neopixel/index.md
      - Binary Clock:   
        - Introduction: kits/neopixel/binary-clock/index.md
        - Assembly: kits/neopixel/binary-clock/assembly.md
        - Code: kits/neopixel/binary-clock/code.md
        - Prompt: kits/neopixel/binary-clock/prompt.md
        - Alternative Layouts: kits/neopixel/binary-clock/alternative-layouts.md
      - 7 Segment Clock:
        - Introduction: kits/neopixel/seven-segment-clock/index.md
        - Assembly: kits/neopixel/seven-segment-clock/assembly.md
        - Light Diffusion: kits/neopixel/seven-segment-clock/03-light-diffusion.md
        - Code: kits/neopixel/seven-segment-clock/code.md
        - Prompt: kits/neopixel/seven-segment-clock/prompt.md
      - Fibonacci Clock:
        - Introduction: kits/neopixel/fibonacci-clock/index.md
        - Assembly: kits/neopixel/fibonacci-clock/assembly.md
        - Code: kits/neopixel/fibonacci-clock/code.md
        - GenAI Prompt: kits/neopixel/fibonacci-clock/prompt.md
    - SSD1306 I2C:
      - Introduction: kits/ssd1306-i2c/index.md
      - Assembly: kits/ssd1306-i2c/assembly.md
      - Code: kits/ssd1306-i2c/code.md
      - Adjusting the Display Layout: kits/ssd1306-i2c/adjusting-digit-display.md
      - Integrating Localtime: kits/ssd1306-i2c/integrating-localtime.md
      - Setting the Time: kits/ssd1306-i2c/setting-time.md
      - GenAI Prompt: kits/ssd1306-i2c/prompt.md
    - Large OLED:
      - Introduction: kits/oled-large/index.md
      - Assembly: kits/oled-large/01-assembly.md
      - Blink: kits/oled-large/00-blink.md
      - Hello World: kits/oled-large/01-hello-world.md
      - Display Config: kits/oled-large/02-display-config.md
      - I2C Scanner: kits/oled-large/02-i2c-scanner.md
      - Set RTC From Localtime: kits/oled-large/02-set-rtc-from-localtime.md
      - Button Test: kits/oled-large/05-button-test.md
      - Display Local Time Raw: kits/oled-large/03-display-localtime-raw.md
      - Display Local Time Formatted: kits/oled-large/04-display-localtime-formatted.md
      - Display Clock Hands:  kits/oled-large/10-clock-hands.md
      - 7-Segment: kits/oled-large/10-draw-seven-segments.md
      - Segment Thickness: kits/oled-large/11-draw-thickness.md
      - Digital Clock: kits/oled-large/15-digital-clock.md
    - Stopwatch: kits/stopwatch/index.md
    - Wireless OLED: kits/oled-wireless/index.md
    - SH1106 OLED: kits/sh1106/index.md
    - ST7735: 
      - Intro: kits/st7735/index.md
      - Hello World: kits/st7735/hello-world.md
      - Single Digit: kits/st7735/single-digit.md
      - Four Digits: kits/st7735/drawing-four-digits.md
      - Minimize Flicker: kits/st7735/dirty-drawing.md
      - Scaling Fonts: kits/st7735/scaling-fonts.md
      - Multiple Fonts: kits/st7735/multiple-fonts.md
      - Set Buttons: kits/st7735/set-mode-buttons.md
    - ILI9341:
      - Introduction: kits/ili9341/index.md
      - Rainbow Test: kits/ili9341/01-rainbow-test.md
      - Hardware Config: kits/ili9341/02-config.md
      - Fonts: kits/ili9341/03-multiple-fonts.md
    - GC9A01:
      - Introduction: kits/gc9a01/index.md
      - Hello World: kits/gc9a01/01-hello-world.md
      - Display Time: kits/gc9a01/02-display-time.md
      - Display Hand: kits/gc9a01//03-display-hand.md
      - Cycle Fonts: kits/gc9a01/04-cycle-fonts.md
      - Draw Ticks: kits/gc9a01/05-draw-ticks.md
      - Watch Face: kits/gc9a01/09-watch-face.md
      - Draw 12 Digits: kits/gc9a01/07-draw-12-digits.md
      - Draw Filled Triangle: kits/gc9a01/08-draw-filled-triangle.md
    - LILYGO SY7789:
      - Introduction: kits/lilygo/index.md
    - Waveshare:
      - Introduction: kits/waveshare-lcd/index.md
      - Hello World: kits/waveshare-lcd/01-hello-world.md
      - Display Text: kits/waveshare-lcd/02-display-text.md
      - Color Lab: kits/waveshare-lcd/02-color-test.md
      - Drawing Hands: kits/waveshare-lcd/03-drawing-hands.md
      - Font Lab: kits/waveshare-lcd/04-5x8-font.md
    - MAX7219: kits/max7219/index.md
    - E-Paper Clock: 
      - Intro: kits/e-paper/index.md
    - Waveshare E-Paper:
      - Intro: kits/waveshare-e-paper/index.md

  - MicroSims:
    - List of MicroSims: sims/index.md
    - Binary Number: sims/binary-number/index.md
    - Binary Clock: sims/binary-clock/index.md
    - Templates: sims/templates/index.md
    - Learning Graph: sims/learning-graph/index.md
    - Four Digit Display: sims/4-digits/index.md
    - Analog Clock Face: sims/analog-clock/index.md
    - Stopwatch: sims/stopwatch/index.md
    - Seven Segment Display: sims/seven-segment-display/index.md
    - Clock Face Themes: sims/themes/index.md
    - Battery Drain: sims/battery-drain/index.md
    - Shift Register: sims/shift-register/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Course Description: prompts/01-course-description.md
    - Concept Enumeration: prompts/02-concept-enumeration.md
    - Concept Dependencies: prompts/03-concept-dependency.md
    - Concept Taxonomies: prompts/04-concept-taxonomy.md
    - Taxonomy Assignments: prompts/05-taxonomy-assignment.md
    - Generating a Banner Image: prompts/06-banner-image.md
    - Generating a FAQ: prompts/07-faq.md
    - Generating a Glossary of Terms: prompts/08-glossary.md
    - OLED Code Generation: prompts/09-oled-test.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - References: references.md
  - Contact: contact.md
  - faq.md
# Dan's Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  custom_dir: custom-theme
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  extra_css:
    - styles/custom.css
  logo: img/logo-180x180.png
  favicon: img/favicon.ico
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - abbr
  - md_in_html
  - pymdownx.highlight:
      linenums: true
  # enable LaTeX extensions
  - pymdownx.arithmatex:
      generic: true
extra_css:
  - css/extra.css
extra_javascript:
  - js/extra.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-EKTEBLZ2KP
