site_name: MicroPython Clocks and Watch
site_description: 'Resources for teaching drawing on a watch face. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/micropython-watch'

nav:
  - Home: index.md
  - Setup:
    - Parts: setup/parts.md
  - Lessons:
    - Get Local Time: lessons/01-get-local-time.md
    - Display Text: lessons/02-display-text.md
  - Kits:
    - Introduction: kits/index.md
    - LILYGO: kits/lilygo.md
    - Waveshare: kits/waveshare.md
  - Contact: contact.md
# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.jpg
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  include_sidebar: true
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-EKTEBLZ2KP
