site_name: "Clocks and Watches with AI"
site_description: 'Designing and Building and Clock and Watches with MicroPython and AI.  This projects uses low-cost parts, MicroPython and AI to teach computational thinking.'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
site_url: 'https://dmccreary.github.io/micropython-clocks-and-watches'
repo_url: 'https://github.com/dmccreary/micropython-clocks-and-watches'

nav:
  - Home: index.md
  - About: about.md
  - Course Description: course-description.md
  - Setup:
    - Introduction: setup/index.md
    - Desktop Setup: setup/01-desktop.md
    - Purchasing Parts: setup/02-purchasing-parts.md
    - Cable Harness: setup/03-display-cable-harness.md
    - LED Clocks: setup/04-led-clocks.md
    - AI in the Classroom: setup/05-ai-in-the-classroom.md
  - Lessons:
    - Introduction: lessons/index.md
    - Timekeeping Architecture: lessons/01-timekeeping-architecture.md
    - Hardware Config Files: lessons/00-hardware-config.md
    - Get Local Time: lessons/01-get-local-time.md
    - Drawing Coordinates: lessons/01-drawing-coordinates.md
    - Displaying Text: lessons/02-display-text.md
    - Drawing a Clock Face: lessons/03-drawing-face.md
    - Larger Fonts: lessons/04-larger-fonts.md
    - Buttons: lessons/05-buttons.md
    - Setting Time: lessons/06-setting-time.md
    - Drawing 7-Segment Digits: lessons/07-drawing-digits.md
    - Digit Functions: lessons/09-digit-functions.md
    - Draw Time Functions: lessons/12-draw-time-functions.md
    - About Real Time Clocks: lessons/13-real-time-clocks.md
    - Scale Testing: lessons/15-scale-testing.md
    - Draw Performance: lessons/06-draw-performance.md
    - ILI9341 Display: lessons/30-ili9341.md
    - Machine Info: lessons/40-machine-info.md
    - DS1307: lessons/50-ds1307-breadboard.md
    - Adding Sound: lessons/60-sound.md/index.md
    - Powering Your Clock and Watch: lessons/70-power/index.md

  - Kits:
    - Introduction Kits: kits/index.md
    - TM1637 LED Kit:
      - Intro: kits/tm1637/index.md
      - Manually Setting Time: kits/tm1637/manual-time-setting.md
      - Running the Clock: kits/tm1637/running-clock.md

    - LED Displays: 
      - Intro: kits/led-displays/index.md
      - Simple TM1637 Display: kits/led-displays/clock-simple.md
      - Shift Register Displays:
        - Intro: kits/shift-register-clock/index.md
        - kits/led-displays/shift-register-displays.md
        - kits/shift-register-clock/clock-main.md
        - kits/shift-register-clock/sample-prompt.md
      - Reference: kits/led-displays/reference.md
    - LED Strip Kits: 
      - Introduction: kits/led-strips/index.md
      - Binary Clock: kits/led-strips/01-binary-clock.md
      - 7 Segment Clock: kits/led-strips/02-seven-segment-clock.md
    - SSD1306 I2C:
      - Introduction: kits/ssd1306-i2c/index.md
      - Adjusting the Display Layout: kits/ssd1306-i2c/adjusting-digit-display.md
      - Integrating Localtime: kits/ssd1306-i2c/integrating-localtime.md
      - Setting the Time: kits/ssd1306-i2c/setting-time.md
    - Large OLED:
      - Introduction: kits/oled-large/index.md
      - Hello World: kits/oled-large/01-hello-world.md
      - Config: kits/oled-large/02-hello-config.md
      - Display Time: kits/oled-large/02-display-time.md
      - Display Localtime: kits/oled-large/03-display-localtime.md
      - Display Localtime Updates: kits/oled-large/04-display-localtime-updates.md
      - Display Clock Hands:  kits/oled-large/05-clock-hands.md
      - 7-Segment: kits/oled-large/10-draw-seven-segments.md
      - Segment Thickness: kits/oled-large/11-draw-thickness.md
      - Digital Clock: kits/oled-large/15-digital-clock.md
    - Wireless OLED: kits/oled-wireless/index.md
    - SH1106 OLED: kits/sh1106/index.md
    - ILI9341:
      - Introduction: kits/ili9341/index.md
      - Rainbow Test: kits/ili9341/01-rainbow-test.md
      - Hardware Config: kits/ili9341/02-config.md
      - Fonts: kits/ili9341/03-multiple-fonts.md
    - GC9A01:
      - Introduction: kits/gc9a01/index.md
      - Hello World: kits/gc9a01/01-hello-world.md
      - Display Time: kits/gc9a01/02-display-time.md
      - Display Hand: kits/gc9a01//03-display-hand.md
      - Cycle Fonts: kits/gc9a01/04-cycle-fonts.md
      - Draw Ticks: kits/gc9a01/05-draw-ticks.md
      - Watch Face: kits/gc9a01/09-watch-face.md
      - Draw 12 Digits: kits/gc9a01/07-draw-12-digits.md
      - Draw Filled Triangle: kits/gc9a01/08-draw-filled-triangle.md
    - LILYGO SY7789:
      - Introduction: kits/lilygo/index.md
    - Waveshare:
      - Introduction: kits/waveshare/index.md
      - Hello World: kits/waveshare/01-hello-world.md
      - Display Text: kits/waveshare/02-display-text.md
      - Color Lab: kits/waveshare/02-color-test.md
      - Drawing Hands: kits/waveshare/03-drawing-hands.md
      - Font Lab: kits/waveshare/04-5x8-font.md
    - MAX7219: kits/max7219/index.md
    - Fibonacci Clock:
      - Intro: kits/fibonacci-clock/index.md
    - E-Ink: 
      - Intro: kits/e-ink/index.md
  - MicroSims:
    - List of MicroSims: sims/index.md
    - sims/binary-clock/index.md
    - sims/templates/index.md
    - sims/learning-graph/index.md
    - sims/4-digits/index.md
    - sims/analog-face/index.md
    - sims/learning-graph/index.md
    - sims/seven-segments/index.md
    - sims/themes/index.md
  - Prompts:
    - Introduction: prompts/index.md
    - Course Description: prompts/01-course-description.md
    - Concept Enumeration: prompts/02-concept-enumeration.md
    - Concept Dependencies: prompts/03-concept-dependency.md
    - Concept Taxonomies: prompts/04-concept-taxonomy.md
    - Taxonomy Assignments: prompts/05-taxonomy-assignment.md
    - Generating a Banner Image: prompts/06-banner-image.md
    - Generating a FAQ: prompts/07-faq.md
    - Generating a Glossary of Terms: prompts/08-glossary.md
    - OLED Code Generation: prompts/09-oled-test.md
  - Glossary: glossary.md
  - FAQ: faq.md
  - References: references.md
  - Contact: contact.md
  - faq.md
# Dan's Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  name: material
  custom_dir: custom-theme
  icon:
    previous: fontawesome/solid/angle-left
    next: fontawesome/solid/angle-right
  extra_css:
    - styles/custom.css
  logo: img/clock-icon.png
  favicon: img/favicon.ico
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  include_sidebar: true
  features:
    - content.code.copy
    - navigation.expand
    - navigation.path
    - navigation.prune
    - navigation.indexes
    - toc.follow
    - navigation.top
    # this adds the prev and next icons in the footer
    - navigation.footer
plugins:
  - search
extra_javascript:
  # - js/mathjax.js
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js
#  - social
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - abbr
  - attr_list
  - md_in_html
  - pymdownx.highlight:
      linenums: true
  # enable LaTeX extensions
  - pymdownx.arithmatex:
      generic: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-EKTEBLZ2KP
