site_name: MicroPython Clocks and Watch
site_description: 'Resources for teaching drawing on a watch face. All content licensed Creative Commons ShareAlike Attribution Noncommercial'
site_author: 'Dan McCreary'
repo_name: 'GitHub Repo'
repo_url: 'https://github.com/dmccreary/micropython-watch'

nav:
  - Home: index.md
  - About: about.md
  - Setup:
    - Parts: setup/parts.md
  - Lessons:
    - Introduction: lessons/index.md
    - Hardware Config: 00-hardware-config.md
    - Drawing Coordinates: lessons/01-drawing-coordinates.md
    - Displaying Text: lessons/02-display-text.md
    - Drawing a Clock Face: lessons/03-drawing-face.md
    - Larger Fonts: lessons/04-larger-fonts.md
    - Hardware Config Files: lessons/00-hardware-config.md
    - Get Local Time: lessons/01-get-local-time.md
    - Drawing Digits: lessons/07-drawing-digits.md
    - Buttons: lessons/05-buttons.md
    - Draw Performance: lessons/06-draw-performance.md
    - Drawing Digits: lessons/drawing-digits.md
  - Kits:
    - Introduction to Watch Kits: kits/index.md
    - Pico with OLED:
      - Introduction: kits/pico-oled/index.md
    - ILI9341:
      - Introduction: kits/ili9341/index.md
      - Rainbow Test: kits/ili9341/01-rainbow-test.md
      - Hardware Config: kits/ili9341/02-config.md
    - GC9A01:
      - Introduction: kits/gc9a01/index.md
      - Hello World: kits/gc9a01/01-hello-world.md
      - Display Time: kits/gc9a01/02-display-time.md
      - Display Hand: kits/gc9a01//03-display-hand.md
      - Cycle Fonts: kits/gc9a01/04-cycle-fonts.md
      - Draw Ticks: kits/gc9a01/05-draw-ticks.md
      - Draw 12 Digits: kits/gc9a01/07-draw-12-digits.md
      - Draw Filled Triangle: kits/gc9a01/08-draw-filled-triangle.md
    - LILYGO SY7789:
      - Introduction: kits/lilygo/index.md
    - Waveshare:
      - Introduction: kits/waveshare/index.md
      - Hello World: kits/waveshare/01-hello-world.md
      - Display Text: kits/waveshare/02-display-text.md
      - Color Lab: kits/waveshare/02-color-test.md
      - Drawing Hands: kits/waveshare/03-drawing-hands.md
      - Font Lab: kits/waveshare/04-5x8-font.md
  - Contact: contact.md

# CoderDojo Microsite Standards from here down
edit_uri: 'blob/master/docs'
theme:
  # should be name: material
  name: material
  logo: img/coderdojo-logo.jpg
  palette:
    primary: '#642580'
    accent: '#41BAC1'
  include_sidebar: true
plugins:
  - search
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - pymdownx.highlight:
      linenums: true
extra:
  analytics:
    provider: google
    # https://analytics.google.com/analytics/web/#/a1420179p349994530/admin/streams/table/4433129821
    property: G-EKTEBLZ2KP
